### ISSUE TITLE
Failed to enable unit: Unit file snap.shadowsocks-libev.ss-server-daemon.service does not exist

### ISSUE THREAD

**Issue by qnyblog** [complexorganizations/shadowsocks-manager#15]
Please help

Failed to enable unit: Unit file snap.shadowsocks-libev.ss-server-daemon.service does not exist.
Failed to start snap.shadowsocks-libev.ss-server-daemon.service: Unit snap.shadowsocks-libev.ss-server-daemon.service not found.
Config File ---> /var/snap/shadowsocks-libev/common/etc/shadowsocks-libev/config.json
Shadowsocks Server IP: []
Shadowsocks Server Port: 80
Shadowsocks Server Password: TiViucXWyGIloowHkRrH5Fx7wnEm2R8SvQ==
Shadowsocks Server Encryption: aes-256-gcm
Shadowsocks Server Mode: tcp_only

**Comment by ghost** [comment]
Hey,
They stopped supporting it, will update it soon.
https://github.com/shadowsocks/shadowsocks-libev

**Comment by qnyblog** [comment]
Thank you

**Comment by ghost** [comment]
Hey,
This is the first item on my to-do list right now, and it's 11 p.m. for me, so I'll update it to utilize the updated shadowsocks-rust first thing tomorrow morning.

**Comment by qnyblog** [comment]
Thank you, have a nice day

**Comment by ghost** [comment]
https://github.com/complexorganizations/shadowsocks-manager/pull/16

**Comment by ghost** [comment]
@qnyblog 
Try it now, since its compiling from source it needs more than 2GB ram.

Its not complete but soon it will be, the installer is ready but the other features are not.

**Comment by qnyblog** [comment]
Thank you

**Comment by ghost** [comment]
@qnyblog
Its ready now, try it if u want.

**Comment by qnyblog** [comment]
Thank you, have a good day.
